### ISSUE TITLE
Loading a 3rd-Party Angular App asynchronously

### ISSUE THREAD

**Issue by stephanrauh** [VinceZK/Portal#1]
Does the portal allow to load a third-party Angular app asynchronously?

I don't think of a loose URL integration, but of loading the front-end of an independent microservice. In theory, it's possible to embed such an Angular application in the content area. 

Most of the time, the Angular router does the trick just fine, but only if the 3rd-party library is part of the portal application. However, I want to integrate a UI that's a completely different deployment unit.

Any ideas?

**Comment by VinceZK** [comment]
This is considered at the beginning. I was thinking of building a APP installer. When, for example, a new APP is delivered through NPM/GitHub, the installer tries to download it to its "app" folder and registers it. In this way, the asynchronously navigation is also achieved. I plan to do check if Angular CLI can do this trick. 

This work is planned next year. As currently, I am focus on another project "json-on-relations". Which is a framework for fast building enterprise CRUD applications. It should be finished before the APP installer.

**Comment by VinceZK** [comment]
For APPs that are built on other UI frameworks, like React, then only URL navigation is possible.

**Comment by stephanrauh** [comment]
In the meantime, I've learned how to create a WebComponent with Angular 6 or 7, and how to load it lazily into an existing Angular portal application. We'll publish the source code soon. Well, as soon as our daily chores allow. :)

I'm sure the same approach also works with WebComponents created with React, Vue.js, or plain Vanilla.js.
